
services:
  ai-reviewer-api:
    build:
      context: .
      dockerfile: AIReviewerAPI/Dockerfile
    container_name: ai-reviewer-api
    ports:
      - "7041:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OpenAI__ApiKey=${GEMINI_API_KEY}
      - Groq__ApiKey=${GROQ_API_KEY}
      - Together__ApiKey=${TOGETHER_API_KEY}
      - Smtp__Host=${Smtp__Host}
      - Smtp__Port=${Smtp__Port}
      - Smtp__User=${Smtp__User}
      - Smtp__Password=${Smtp__Password}
      - Smtp__FromName=${Smtp__FromName}

  code-reviewer:
    build:
      context: .
      dockerfile: CodeReviewer/Dockerfile
    container_name: code-reviewer
    ports:
      - "7091:8090"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8090
      - ApiBaseUrl=http://ai-reviewer-api:8080/
    volumes:
      - dp_keys:/root/.aspnet/DataProtection-Keys

volumes:
  dp_keys:

